# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Hongil Son
baseurl:        ""
url:            "http://www.sonhl0723.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:         
  name:         Hongil
  url:          http://sonhl0723.github.io/
  email:        sonhl0723@naver.com
  github:       sonhl0723
  twitter:      

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/sonhl0723/sonhl0723.github.io